// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgAHc_1dfWX4ZvunCcwFG4jBV5sbxpcNA',
    appId: '1:1086579710745:web:5dded727973898a1230388',
    messagingSenderId: '1086579710745',
    projectId: 'chat-app-dfbea',
    authDomain: 'chat-app-dfbea.firebaseapp.com',
    storageBucket: 'chat-app-dfbea.firebasestorage.app',
    measurementId: 'G-BBXFF5JR4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3nXtS0CBbA3iVIyTDOwdfjH2-rrdyLWk',
    appId: '1:1086579710745:android:f54d48e45ee4d14b230388',
    messagingSenderId: '1086579710745',
    projectId: 'chat-app-dfbea',
    storageBucket: 'chat-app-dfbea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZ3hyNTbOBWKgnc0y6Kqsy3bjBIMm3Cw',
    appId: '1:1086579710745:ios:ee2a599c3d77249b230388',
    messagingSenderId: '1086579710745',
    projectId: 'chat-app-dfbea',
    storageBucket: 'chat-app-dfbea.firebasestorage.app',
    androidClientId: '1086579710745-3dfe226plep95a5la2iko0pl264ipc6n.apps.googleusercontent.com',
    iosClientId: '1086579710745-4cvji75jvna799qktu2agc7de88vg77h.apps.googleusercontent.com',
    iosBundleId: 'com.example.macroGlobalTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgZ3hyNTbOBWKgnc0y6Kqsy3bjBIMm3Cw',
    appId: '1:1086579710745:ios:ee2a599c3d77249b230388',
    messagingSenderId: '1086579710745',
    projectId: 'chat-app-dfbea',
    storageBucket: 'chat-app-dfbea.firebasestorage.app',
    androidClientId: '1086579710745-3dfe226plep95a5la2iko0pl264ipc6n.apps.googleusercontent.com',
    iosClientId: '1086579710745-4cvji75jvna799qktu2agc7de88vg77h.apps.googleusercontent.com',
    iosBundleId: 'com.example.macroGlobalTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgAHc_1dfWX4ZvunCcwFG4jBV5sbxpcNA',
    appId: '1:1086579710745:web:75dc2674bf67c0bc230388',
    messagingSenderId: '1086579710745',
    projectId: 'chat-app-dfbea',
    authDomain: 'chat-app-dfbea.firebaseapp.com',
    storageBucket: 'chat-app-dfbea.firebasestorage.app',
    measurementId: 'G-DCDRV8QHX5',
  );
}
